name: github expression that runs on issues
on: push
#  issues:
#    types: [opened, edited, milestoned]
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: printing github expressions
        run: echo "${{ toJSON(github) }}"
      






    


